[pytest]
addopts = [
    "-v",
    "-ra",
    "--strict-markers",
    "--strict-config",
    "--cov=bookvie",
    "--cov-report=term-missing",
    "--cov-report=html",
]
markers = [
    "smoke: subset of tests"
]