from typing import TypeVar, Protocol, Sequence

from .models import Book, Reading, ReadingSequence

T = TypeVar("T")


class Repository(Protocol[T]):
    def add(self, entity: T) -> T: ...

    def save(self, entity: T) -> T: ...

    def get(self, entity_id: str) -> T | None: ...

    def get_or_raise(self, entity_id: str) -> T: ...

    def list_all(self) -> list[T]: ...

    def delete(self, entity_id: str) -> bool: ...

    def count(self) -> int: ...


class BookRepository(Repository[Book], Protocol):
    def get_man(self, ids: Sequence[str]) -> dict[str, Book]: ...

    def search_by_title(self, fragment: str) -> list[Book]: ...


class ReadingRepository(Repository[Reading], Protocol):
    def get_for(self, book_id: str, sequence_id: str) -> Reading | None: ...

    def list_for_sequence(self, sequence_id: str) -> list[Reading]: ...

    def list_for_book(self, book_id: str) -> list[Reading]: ...

    def delete_for(self, book_id: str, sequence_id: str) -> bool: ...

    def delete_for_sequence(self, sequence_id: str) -> int: ...

    def delete_for_book(self, book_id: str) -> int: ...


class SequenceRepository(Repository[ReadingSequence], Protocol):
    def containing_book(self, book_id: str) -> list[ReadingSequence]: ...
